######################################################################
# Automatically generated by qmake (2.01a) ven. déc. 10 12:58:15 2021
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += calc_predictability.h calc_probability_density.h defs.h read_lammps.h
SOURCES += calc_predictability.cpp \
           calc_probability_density.cpp \
           main.cpp \
           read_lammps.cpp
